# generated by datamodel-codegen:
#   filename:  burn_supply.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class BurnSupplyParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    amount: str
    issuer_id: str
