# generated by datamodel-codegen:
#   filename:  mint.json

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel, Extra


class TokenIdAmount(BaseModel):
    class Config:
        extra = Extra.forbid

    amount: str
    token_id: str


class Infusion(BaseModel):
    class Config:
        extra = Extra.forbid

    token_address: str
    token_id_amounts: List[TokenIdAmount]


class Split(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    pct: str


class MintParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    amount: str
    infusions: List[Infusion]
    max_per_address: str
    metadata: Dict[str, str]
    no_transfers_until: Optional[str]
    req_verified_to_own: bool
    royalty: str
    splits: List[Split]
