# generated by datamodel-codegen:
#   filename:  buy.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Extra


class BuyParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    auction_id: str
    amount: str
    proxy: Optional[str]
