# generated by datamodel-codegen:
#   filename:  bid.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class BidParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    auction_id: str
    bid_amount_fa2: str
