# generated by datamodel-codegen:
#   filename:  create_auction.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Extra


class CurrencyItem(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    nat: str


class Token(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    nat: str


class CreateAuctionParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    bid_amount: str
    currency: Optional[CurrencyItem]
    end_timestamp: str
    require_verified: bool
    token: Token
    token_amount: str
