# generated by datamodel-codegen:
#   filename:  update_profile.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class UpdateProfileParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    metadata: str
    name: str
